id: P010585
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7013
  title: ས་སྐྱའི་གདན་རབས།
  author: ''
  volumes:
    b789187a9c7941baa9c9a0e645edf286:
      image_group_id: I3CN7015
      title: ''
      volume_number: 1
      total_pages: 288
