id: P010585
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:15.577252
source_metadata:
  id: bdr:W3CN7013
  title: ས་སྐྱའི་གདན་རབས།
  author: ''
  volumes:
    b789187a9c7941baa9c9a0e645edf286:
      image_group_id: I3CN7015
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
